#!/usr/bin/env bash
# dk-post-commit-convention.sh — PostToolUse(Bash).
#
# After a commit lands, check its subject against Conventional Commits and, if it does not
# conform, say so while `--amend` is still free.
#
# WHY THIS FIRES *AFTER* THE COMMIT RATHER THAN BLOCKING IT
#
# ADD-SDD's equivalent (gsd-validate-commit.sh) is a PreToolUse hook that returns a block decision
# with the harness's blocking status code. That is the more forceful design and it is
# deliberately NOT what this does: CONTRACTS.md invariant 2 says no hook in this directory blocks
# a tool call, on the grounds that a hook which breaks a session is worse than one that does
# nothing. A malformed commit subject is cheap to fix and has not left the machine yet, so it does
# not clear that bar. Blocking would also misfire on the legitimate cases — a merge commit, a
# revert, a fixup, an amend that is itself the fix — each of which would need its own exemption in
# the blocking path, and every missing exemption is a wedged session.
#
# WHY IT MATTERS AT ALL, given the message is only a string: three assets read commit history as
# data. `document-release` and `ship` build CHANGELOG entries from it, and `retro` mines it for
# week-over-week trends. A subject none of them can parse does not error — it silently drops that
# commit out of the changelog and the retro, which is the kind of gap nobody finds later.
#
# The check is subject-line only. Body, trailers and co-author lines are never inspected.

. "$(dirname "$0")/lib/dk-common.sh"

dk_read_stdin
dk_guard

CMD="$(dk_json tool_input.command)"
[ -n "$CMD" ] || exit 0

# Only react to a commit that actually created something. `git commit` with no -m opens an editor
# (the agent does not take that path), and --amend is frequently the fix for this very warning, so
# firing on it would loop the advice back at someone already following it.
printf '%s' "$CMD" | grep -qE '(^|[[:space:]])git[[:space:]]+(-C[[:space:]]+[^[:space:]]+[[:space:]]+)?commit([[:space:]]|$)' || exit 0
printf '%s' "$CMD" | grep -qE '(^|[[:space:]])--amend([[:space:]]|$)' && exit 0

# Read the subject from git rather than parsing it back out of the command string. The command may
# quote the message in any of several ways, may use -F or a heredoc, and may be one segment of a
# compound line; the commit itself is unambiguous. This also means a `git commit` that FAILED
# leaves HEAD untouched and we simply re-read the previous subject — see the dedupe below.
ROOT="$(dk_root)"
SUBJECT="$(git -C "$ROOT" log -1 --pretty=%s 2>/dev/null)"
[ -n "$SUBJECT" ] || exit 0

# A merge or revert subject is generated by git and is conventionally exempt.
case "$SUBJECT" in
  Merge\ *|Revert\ *|"fixup! "*|"squash! "*) exit 0 ;;
esac

# Never warn twice about the same commit. Without this a failed-then-retried commit, or any later
# Bash call in the same turn, re-reads the same HEAD and repeats the nudge.
SHA="$(git -C "$ROOT" rev-parse --short HEAD 2>/dev/null)"
[ -n "$SHA" ] && ! dk_once "commit-$SHA" && exit 0

TYPES='build|chore|ci|docs|feat|fix|perf|refactor|revert|style|test'
PROBLEM=""

if ! printf '%s' "$SUBJECT" | grep -qE "^($TYPES)(\([^)]+\))?!?: .+"; then
  PROBLEM="it does not start with \`<type>: \` — expected one of: $(printf '%s' "$TYPES" | tr '|' ' ')"
elif [ "${#SUBJECT}" -gt 72 ]; then
  PROBLEM="the subject is ${#SUBJECT} characters (over 72), so it will be truncated in logs and release notes"
fi

[ -n "$PROBLEM" ] || exit 0

dk_emit PostToolUse "dk commit convention: the commit just written does not follow Conventional Commits — $PROBLEM. Subject was: \"$SUBJECT\". This is advisory and nothing is blocked, but document-release, ship and retro all parse commit subjects, and a non-conforming one drops out of the CHANGELOG and the retrospective silently. It has not been pushed yet, so \`git commit --amend\` is still the cheap fix. If the message is deliberate, ignore this."
exit 0
